In [1]:
# revise pytorch 
# runs on conda

In [2]:
import numpy as np 
import torch 
import matplotlib.pyplot as plt

/home/anirudh/miniconda3/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
x = torch.randn(2,3)
x

tensor([[ 0.1624,  0.5900, -0.7531],
        [-0.0838, -1.2611,  0.6350]])

In [7]:
x.view(3,2)

tensor([[ 0.1624,  0.5900],
        [-0.7531, -0.0838],
        [-1.2611,  0.6350]])

In [8]:
x.size()

torch.Size([2, 3])

In [9]:
x.add_(torch.ones(2,3))

tensor([[ 1.1624,  1.5900,  0.2469],
        [ 0.9162, -0.2611,  1.6350]])

In [10]:
torch.abs_(x)
x

tensor([[1.1624, 1.5900, 0.2469],
        [0.9162, 0.2611, 1.6350]])